import random
import os,sys
import time
print("")
print("")
time.sleep(1)
print("\033[1;91mLoading...")
time.sleep(5)
os.system("clear")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("pkg install git")
os.system("pkg install socks")
os.system("pkg install python")
os.system("clear")
print("\033[0m[\033[1;91m1\033[0m] \033[1;92mHacker Facebook")
print("\033[0m[\033[1;91m2\033[0m] \033[1;92mHacker Tiktok")
print("\033[0m[\033[1;91m3\033[0m] \033[1;92mHacker Email")
print("\033[0m[\033[1;91m4\033[0m] \033[1;92mHacker Instagram")
print("")
e = input("\033[0m[\033[1;91m*\033[0m] \033[1;92mEnter the funcotions : \033[1;96m")
if e == "1":
	print("")
	print("")
	id = input("\033[0mID target : ")
	print("")
	time.sleep(3)
	print("\033[1;93mLoding..")
	print("")
	time.sleep(2)
	print("")
	print(f"\033[1;96mUsername : {id}")
	print("Password : " + str(random.randint(100000,900000)))
	
if e == "2":
	print("")
	print("")
	id = input("\033[0mID target : ")
	print("")
	time.sleep(3)
	print("\033[1;93mLoding..")
	print("")
	time.sleep(2)
	print("")
	print(f"\033[1;96mUsername : {id}")
	print("Password : " + str(random.randint(100000,900000)))
	
if e == "3":
	print("")
	print("")
	id = input("\033[0mEmail : ")
	print("")
	time.sleep(3)
	print("\033[1;93mLoding..")
	print("")
	time.sleep(2)
	print("")
	print(f"\033[1;96mUsername : {id}")
	print("Password : " + str(random.randint(100000,900000)))
	
if e == "4":
	print("")
	print("")
	id = input("\033[0mID target : ")
	print("")
	time.sleep(3)
	print("\033[1;93mLoding..")
	print("")
	time.sleep(2)
	print("")
	print(f"\033[1;96mUsername : {id}")
	print("Password : " + str(random.randint(100000,900000)))

else:
   print("\033[1;92mError")
